apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl 
spec:
  acme:
    email: {{ .Values.zerossl_email }}
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: "uAOxe7WsWUN0HAkadE-gyA"
      # {{ .Values.zerossl_eab_hmac_key_id }}
      keySecretRef:
        name: zerossl-eab-hmac-key 
        key: secret
      keyAlgorithm: HS256
    privateKeySecretRef:
        name: prod 
    solvers:
    - http01:
        ingress:
          class: istio
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digital-ocean-secret 
            key: token 
