# Labels
project: cinema
component: movies

image:
  repository: mmorejon/cinema-movies
  tag: 1.1.1
  pullPolicy: IfNotPresent
## replicas number for each component
replicas: 1

resources: {}
  #  requests:
  #    memory: 20Mi
  #    cpu: 100m
  #  limits:
  #    memory: 700Mi

# Service port
service:
  port: 8080

# Ingress
ingress:
  enabled: true
  host: movies.local

# Environment values to expose user service and connect with MongoDB service.
config:
  server: 0.0.0.0
  mongodbHost: mongodb-replicaset-client.default.svc.cluster.local
  mongodbUser:
  mongodbPwd:
  database: movies